name: .NET Core Build and Deploy (AppSvc)

on: [push]

env:
  AZURE_RESOURCE_GROUP: blazor-deployment-samples
  AZURE_APP_NAME: bwasm-linux-server

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Publish with dotnet
      run: dotnet publish --configuration Release 
    
    - name: Publish artifacts
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: bin/Release/netstandard2.1/publish/BlazorApp27/dist

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    # Download artifacts
    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: webapp

    # Deploy to App Service Linux
    - uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.BWASM_PUB_PROFILE }}
        app-name: ${{ env.AZURE_APP_NAME }}
        package: blazor-deploy-sample
